[package]
name = "channel"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
license = "Apache-2.0/MIT"

[dependencies]
crossbeam-epoch = { git = "https://github.com/jeehoonkang/crossbeam-epoch", branch = "channel" }
parking_lot = "0.4.4"
rand = "0.3"
